---
driver:
  name: vagrant
  customize:
    memory: 1536
    cpus: 2

provisioner:
  name: chef_solo
  require_chef_omnibus: 12.3.0
  environments_path: test/environments

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7.2
  - name: centos-6.6
  - name: centos-5.11

suites:
  - name: default
    driver:
      vm_hostname: ubuntu1604
    provisioner:
      solo_rb:
        environment: beta
    run_list:
      - recipe[vast-java]
    attributes:
      datacenter:
        city: oakland
      java_versions:
        beta:
          - "9.0.4"
          - "8u162"
